# version format
version: 1.7.{build}

# build only tags
skip_non_tags: true

# image
image: Visual Studio 2017

# build platform
platform: x64
configuration: Release

# clone directory
clone_folder: c:\xmrigCC

install:
  - appveyor DownloadFile https://dl.bintray.com/boostorg/release/1.68.0/binaries/boost_1_68_0-msvc-14.1-64.exe -FileName boost_1_68_0-msvc-14.1-64.exe
  - boost_1_68_0-msvc-14.1-64.exe /VERYSILENT /DIR="C:\boost_1_68_0"
  - appveyor DownloadFile  https://www.python.org/ftp/python/2.7.15/python-2.7.15.amd64.msi -FileName python-2.7.15.amd64.msi
  - msiexec /qn /i python-2.7.15.amd64.msi 
  - set PYTHON=C:\Python27\python.exe
  - git clone https://github.com/libuv/libuv c:\libuv

build_script:
  - cd c:\libuv
  - call vcbuild.bat release vs2017 x64 static
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
  - cd c:\xmrigCC
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 .. -DUV_INCLUDE_DIR="c:\libuv\include" -DUV_LIBRARY="c:\libuv\Release\lib\libuv.lib" -DBOOST_ROOT=C:\boost_1_68_0
  - msbuild xmrig.sln /p:Configuration=Release

after_build:
- ps: | # package artifacts
    7z a -m0=LZMA2 -mx9 c:\xmrigCC\xmrigCC-msvc-win64.7z c:\xmrigCC\build\Release\*

artifacts:
- path: xmrigCC-msvc-win64.7z
